---
title: Software Testing
description: "Ensuring Python Program Correctness"
date: 2025-09-29
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - Instructor-led deep-dive on software testing for Python programs
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - [DEPC2 presentation](/slides/depc/weekfive/index.qmd) completed through the
  use of [Quarto](https://quarto.org/), [RevealJS](https://revealjs.com/),
  [Markdown](https://www.markdownguide.org/), [Git](https://git-scm.com/),
  [GitHub](https://github.com/), and the [GitHub Flow
  model](https://docs.github.com/en/get-started/quickstart/github-flow)
  - Presentation available, in final form, as a pull request in the [GitHub
  repository for the course web
  site](https://github.com/prosegrammers/www.prosegrammers.com), no later than
  11:59 PM
  - Each DEPC2 team member must use Git and their own GitHub account to commit
  their work to the [pull
  request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
  for their team's slides
- {{< iconify fa6-solid people-line size=18px >}} **Wednesday**:
  - Team-based delivery of [DEPC2
  presentation](/slides/depc/weekfive/index.qmd)
  - Release the schedule for two types of presentations in next module:
     - Document Engineering Concept Overviews (DECO)
     - Document Engineering Project Critiques (DEPC)
- {{< iconify fa6-solid gears size=18px >}} **Wednesday Laboratory**:
  - Finish working on first document engineering tool-building project
  - Students meet with the student technical leaders
  - Students give final in-person demonstration to course instructor
- {{< iconify fa6-solid gears size=18px >}} **Friday**:
  - Submit completed first document engineering tool-building project 
