---
title: Reviewing Python Programming
description: "Understand Python Programming Basics"
date: "2025-09-01"
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - No class due to the fact that it is Labor Day
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - [Diátaxis: A systematic approach to technical documentation authoring]()
  - DECO1 presentation completed through the use of
  [Quarto](https://quarto.org/), [RevealJS](https://revealjs.com/),
  [Markdown](https://www.markdownguide.org/), [Git](https://git-scm.com/),
  [GitHub](https://github.com/), and the [GitHub Flow
  model](https://docs.github.com/en/get-started/quickstart/github-flow).
  - Presentation available, in final form, as a pull request in the [GitHub
  repository for the course web
  site](https://github.com/prosegrammers/www.prosegrammers.com), no later than
  11:59 PM.
  - Each DECO1 team member must use Git and their own GitHub account to commit
  their work through to the [pull
  request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
  for their team's slides.

- {{< iconify fa6-solid people-line size=18px >}} **Wednesday**:
  - Prepare for document engineering presentations and evaluations by teams
  - As outlined in the [syllabus](../../syllabus/index.qmd), teams give two
  types of presentations:
     - Document Engineering Concept Overviews (DECO)
     - Document Engineering Project Critiques (DEPC)
- {{< iconify fa6-solid gears size=18px >}} **Wednesday Laboratory**:
  - Installation of required software tools for document engineering
  - Release the schedule for the two types of presentations:
     - Document Engineering Concept Overviews (DECO)
     - Document Engineering Project Critiques (DEPC)
  - Teams meet to confirm contact information and plan their presentations
- {{< iconify fa6-solid gears size=18px >}} **Friday**:
  - Students demonstrate setup for GitHub, VS Code, and Python through `uv`
