---
title: "Dictionaries for Documents"
description: "Understand details about dictionaries"
date: 2025-10-20
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - Instructor-led deep-dive on dictionaries, including these topics:
    - Storage of key-value pairs
    - Benefits of using dictionaries
    - Adding and removing pairs
    - Accessing values with keys
    - Iterating over dictionaries
  - As needed, instructor review of previous technical topics
- {{< iconify fa6-solid people-line size=18px >}} **Wednesday**:
  - Instructor-led deep-dive on dictionaries
  - See the list of technical topics in the entry for Monday
- {{< iconify fa6-solid gears size=18px >}} **Wednesday Laboratory**:
  - Continue working on second document engineering tool-building project
  - Students meet with the student technical leaders
  - Students give in-person demonstration to course instructor
- {{< iconify fa6-solid gears size=18px >}} **Friday**:
  - Use installed software tools for document engineering skill-check three
  - Complete skill-check three during the in-person classroom session
  - Please review [Week One: Introduction to Document
  Engineering](../../slides/weekone/) for a list of necessary software tools

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weeknine/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Nine: Using Dictionaries for Document Engineering](../../slides/weeknine/)
